function pose = normalize_pose_struct(pose_cfg)
    pose = struct();
    pose.position_m = double(pose_cfg.position_m(:)).';
    pose.orientation_deg = struct( ...
        'yaw', double(pose_cfg.orientation_deg.yaw), ...
        'pitch', double(pose_cfg.orientation_deg.pitch), ...
        'roll', double(pose_cfg.orientation_deg.roll) ...
    );
end