function validate_dynamic_scene_config(cfg)
    required_top = { ...
        'schema_version', ...
        'scene_type', ...
        'scene_id', ...
        'room', ...
        'receiver', ...
        'sources', ...
        'dynamic_render', ...
        'render' ...
    };

    for i = 1:numel(required_top)
        if ~isfield(cfg, required_top{i})
            error('Missing required top-level field: %s', required_top{i});
        end
    end

    if ~strcmp(cfg.scene_type, 'dynamic')
        error('Expected scene_type = dynamic');
    end

    if isempty(cfg.sources)
        error('cfg.sources must contain at least one source');
    end


end