function tests = test_build_room_from_config
    tests = functiontests(localfunctions);
end

function testAppliesExplicitRoomMaterialsInRavenOrder(testCase)
    ctx = struct();
    ctx.manifest = struct('room', make_room_cfg());
    ctx.rpf = MockRavenProject({'ceiling-slot', 'floor-slot', 'north-slot', 'south-slot', 'east-slot', 'west-slot'});

    ctx = build_room_from_config(ctx);

    verifyEqual(testCase, ctx.rpf.shoebox_dims, [4.2 3.6 2.8]);
    verifyEqual(testCase, numel(ctx.rpf.material_calls), 6);
    verifyEqual(testCase, {ctx.applied_room_materials.surface}, ...
        {'ceiling', 'floor', 'north_wall', 'south_wall', 'east_wall', 'west_wall'});
    verifyEqual(testCase, {ctx.rpf.material_calls.slot_name}, ...
        {'ceiling-slot', 'floor-slot', 'north-slot', 'south-slot', 'east-slot', 'west-slot'});
    verifyEqual(testCase, ctx.rpf.material_calls(1).absorp, parse_room_material_file(ctx.manifest.room.material_files.ceiling.material_path).absorp);
    verifyEqual(testCase, ctx.rpf.material_calls(5).scatter, parse_room_material_file(ctx.manifest.room.material_files.east_wall.material_path).scatter);
end

function room = make_room_cfg()
    repo_root = get_repo_root();
    room = struct();
    room.dimensions_m = [4.2 3.6 2.8];
    room.materials = struct( ...
        'north_wall', 'bricks', ...
        'south_wall', 'bricks', ...
        'east_wall', 'glass', ...
        'west_wall', 'wood', ...
        'floor', 'wood', ...
        'ceiling', 'plaster');
    room.material_files = struct( ...
        'north_wall', struct('material_id', 'bricks', 'material_path', fullfile(repo_root, 'assets', 'materials', 'bricks', 'Bricks.mat')), ...
        'south_wall', struct('material_id', 'bricks', 'material_path', fullfile(repo_root, 'assets', 'materials', 'bricks', 'Bricks.mat')), ...
        'east_wall', struct('material_id', 'glass', 'material_path', fullfile(repo_root, 'assets', 'materials', 'glass', 'glass.mat')), ...
        'west_wall', struct('material_id', 'wood', 'material_path', fullfile(repo_root, 'assets', 'materials', 'wood', 'Wood.mat')), ...
        'floor', struct('material_id', 'wood', 'material_path', fullfile(repo_root, 'assets', 'materials', 'wood', 'woodfloor.mat')), ...
        'ceiling', struct('material_id', 'plaster', 'material_path', fullfile(repo_root, 'assets', 'materials', 'plaster', 'mat_scene10_plaster.mat')));
end

function repo_root = get_repo_root()
    test_dir = fileparts(mfilename('fullpath'));
    repo_root = fileparts(fileparts(fileparts(test_dir)));
end
