function tests = test_export_render_metadata
    tests = functiontests(localfunctions);
end

function testWritesCompactMetadataWithoutLegacyOutputCounters(testCase)
    cfg = struct( ...
        'schema_version', '1.0', ...
        'scene_id', 'scene_static_0001', ...
        'job_id', 'job_001', ...
        'scene_type', 'static', ...
        'render', struct('effective_seed', 123, 'seed_source', 'render.seed'));

    result = struct();
    result.fs = 44100;
    result.audio = ones(32, 2);
    result.hrtf_id = 'subject-a';
    result.hrtf_path = 'a.daff';
    result.output = struct('wav_path', 'out.wav', 'metadata_path', 'meta.json', 'project_name', 'project');
    result.summary = struct( ...
        'scene_type', 'static', ...
        'render_backend', 'RAVEN + ITA', ...
        'n_sources', 1, ...
        'room', struct('reverberation', struct( ...
            'metric', 'T30', ...
            'estimated_from', 'room', ...
            'method', 'rpf.getT30', ...
            't30_s', [0.7 0.8 0.9], ...
            'mean_t30_s', 0.8, ...
            'status', 'estimated')), ...
        'sources', struct('source_id', 'src1', 'source_start_time_s', 0.0, 'source_end_time_s', 1.0), ...
        'output_num_samples', 32, ...
        'output_num_channels', 2);

    batch = struct('n_variants', 1, 'scene_type', 'static');
    output_path = [tempname '.json'];
    cleanup = onCleanup(@() delete_if_exists(output_path)); %#ok<NASGU>

    export_render_metadata(cfg, result, output_path, batch);
    meta = jsondecode(fileread(output_path));

    verifyEqual(testCase, meta.scene_id, 'scene_static_0001');
    verifyEqual(testCase, meta.summary.sources.source_end_time_s, 1.0);
    verifyEqual(testCase, meta.summary.room.reverberation.mean_t30_s, 0.8, 'AbsTol', 1e-12);
    verifyEqual(testCase, transpose(meta.summary.room.reverberation.t30_s), [0.7 0.8 0.9], 'AbsTol', 1e-12);
    verifyTrue(testCase, isfield(meta, 'batch'));
    verifyFalse(testCase, isfield(meta, 'output_num_samples'));
    verifyFalse(testCase, isfield(meta, 'output_num_channels'));
end

function delete_if_exists(path_value)
    if isfile(path_value)
        delete(path_value);
    end
end
