function runs = preallocate_static_runs(n_runs)
    runs = repmat(struct( ...
        'hrtf_id', '', ...
        'hrtf_path', '', ...
        'output', struct(), ...
        'audio', [], ...
        'fs', [], ...
        'summary', struct()), 1, n_runs);
end
